server:
  port: 8081
  servlet:
    context-path: /api

spring:
  application:
    name: support
    version: 0.0.1
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  security:
    oauth2:
      client:
        registration:
          keycloak:
            scope: openid, profile
            authorization-grant-type: authorization_code
        provider:
          keycloak:
            user-name-attribute: preferred_username
  datasource:
    driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: validate
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect

  rabbitmq:
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 3000
          max-attempts: 3
    template:
      exchange:
        type: direct
        durable: true
        auto-delete: false
      queue:
        durable: true
        exclusive: false
        auto-delete: false

  flyway:
    enabled: true
    schemas: public
    default-schema: public
    locations: classpath:db/migration
