spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: backend
            client-secret: hD8dQ8n0nQzzpAUbN8RNhyQQGKqqKKVj
        provider:
          keycloak:
            issuer-uri: http://172.17.0.1:8282/realms/support
            jwk-set-uri: http://172.17.0.1:8282/realms/support/protocol/openid-connect/certs
      resourceserver:
        jwt:
          issuer-uri: http://172.17.0.1:8282/realms/support

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: admin
    password: admin
    virtual-host: cpp

    template:
      exchange:
        name: build_notifications
      queue:
        name: build_queue
      binding:
        routing-key: build_notifications_key

  datasource:
    url: jdbc:postgresql://172.17.0.1:5432/support-db
    username: admin
    password: admin

minio:
  accessKey: minioadmin
  secretKey: minioadmin
  url: http://172.17.0.1:9000
  inventoryItemBucketName: inventory-items

elasticsearch:
  host: 172.17.0.1
  port: 9200

secret-key: 123
oAuth_security_schema: my_oAuth_security_schema
keycloak-auth-redirect: http://172.17.0.1:8282/realms/support/protocol/openid-connect/auth
service-url: http://172.17.0.1:8082

keycloak:
  auth-server-url: http://172.17.0.1:8282/auth
  server-url: http://172.17.0.1:8282
  realm: support
  resource: backend
  username: admin
  password: admin
  client-secret: hD8dQ8n0nQzzpAUbN8RNhyQQGKqqKKVj